# Generated by Django 2.2.1 on 2019-05-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190522_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.OrderProduct'),
            preserve_default=False,
        ),
    ]
