# Generated by Django 2.2.1 on 2019-05-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_ordered_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
    ]
