# Generated by Django 2.2 on 2019-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0008_auto_20190528_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
