# Generated by Django 2.2 on 2019-05-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0011_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='shop.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='shop.Product'),
        ),
    ]
