# Generated by Django 2.2 on 2019-05-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190528_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
    ]
