# Generated by Django 2.2 on 2019-05-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190529_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='product',
            new_name='ordered_product',
        ),
    ]
