# Generated by Django 2.2 on 2019-05-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
    ]
