# Generated by Django 2.2 on 2019-05-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_orderitems_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='ordered_product',
            new_name='product',
        ),
    ]
