# Generated by Django 2.2 on 2019-05-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190529_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='price',
        ),
    ]
